name: Linting

on:
  push:
    branches: ["main"]
  pull_request:
    branches: ["main"]

jobs:
  linting:
    name: Linting
    strategy:
      fail-fast: false
      matrix:
        include:
        - {name: black, command: black . --check}
        - {name: flake8, command: flake8 .}
        - {name: isort, command: isort . --check}
        - {name: pylint, command: 'pylint */**.py --evaluation "0 if fatal else max(0, 10 - error - warning)"'}

    runs-on: ubuntu-latest
    steps:
    - name: Checkout
      uses: actions/checkout@v4

    - name: Set up Python
      uses: actions/setup-python@v5
      with:
        python-version-file: pyproject.toml

    - name: Cache pip dependencies
      uses: actions/cache@v4
      with:
        path: ~/.cache/pip
        key: linting-pip-${{ hashFiles('**/pyproject.toml') }}
        restore-keys: |
          linting-pip-

    - name: Install dependencies
      run: |
        python -m pip install --upgrade pip
        python -m pip install -e .[dev]

    - name: Run ${{ matrix.name }}
      run: python -m ${{ matrix.command }}
