name: Build songs-dl

on:
  push:
    tags: "*"

jobs:
  build:
    runs-on: ubuntu-latest
    environment:
      name: production
      url: https://pypi.org/p/songs-dl
    permissions:
      id-token: write

    steps:
    - name: Checkout
      uses: actions/checkout@v3

    - name: Set up Python 3.11
      uses: actions/setup-python@v4
      with:
        python-version: 3.11

    - name: Install dependencies
      run: |
        python -m pip install --upgrade pip
        python -m pip install -e .[build]

    - name: Build package
      run: |
        python -m build

    - name: Publish package to PyPI
      uses: pypa/gh-action-pypi-publish@release/v1
